import React, { useState } from "react";
import "./CompetencyFrameworkPlanner.css";

const CompetencyFramework = () => {
  const [framework, setFramework] = useState({
    department: "",
    jobTitle: "",
    jobLevels: [],
    competencies: [],
  });
  const [generatedDescriptions, setGeneratedDescriptions] = useState([]);
  const [loading, setLoading] = useState(false);

  const updateFramework = (key, value) => {
    setFramework((prev) => ({ ...prev, [key]: value }));
  };

  const autoGenerateDescriptions = async () => {
    if (!framework.department || !framework.jobTitle || !framework.jobLevels.length || !framework.competencies.length) {
      alert("Please fill all fields.");
      return;
    }

    setLoading(true);
    try {
      const response = await fetch("https://interviewappbe-production.up.railway.app/api/generate-competencies", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          department: framework.department,
          jobTitle: framework.jobTitle,
          jobLevels: framework.jobLevels,
          competencies: framework.competencies.map((c) => c.name),
        }),
      });

      if (!response.ok) {
        alert(`Error: ${response.status} - ${response.statusText}`);
        setLoading(false);
        return;
      }

      const data = await response.json();

      if (data.success) {
        setGeneratedDescriptions(data.competencyDescriptions);
        setFramework((prev) => ({
          ...prev,
          competencies: prev.competencies.map((competency, index) => ({
            ...competency,
            descriptions: data.competencyDescriptions[index]?.levels || {},
          })),
        }));
      } else {
        alert("Failed to generate descriptions.");
      }
    } catch (error) {
      console.error("Error generating descriptions:", error);
      alert("An error occurred while generating descriptions.");
    } finally {
      setLoading(false);
    }
  };

  const isFormValid =
    framework.department &&
    framework.jobTitle &&
    framework.jobLevels.length > 0 &&
    framework.competencies.length > 0;

  return (
    <div className="planner-container">
      <h1 className="planner-title">Competency Framework Generator</h1>
      <div className="planner-form">
        <input
          type="text"
          placeholder="Department"
          value={framework.department}
          onChange={(e) => updateFramework("department", e.target.value)}
        />
        <input
          type="text"
          placeholder="Job Title"
          value={framework.jobTitle}
          onChange={(e) => updateFramework("jobTitle", e.target.value)}
        />
        <textarea
          placeholder="Job Levels (comma separated)"
          value={framework.jobLevels.join(", ")}
          onChange={(e) =>
            updateFramework(
              "jobLevels",
              e.target.value.split(",").map((level) => level.trim())
            )
          }
        />
        <textarea
          placeholder="Competencies (comma separated)"
          value={framework.competencies.map((c) => c.name).join(", ")}
          onChange={(e) =>
            updateFramework(
              "competencies",
              e.target.value.split(",").map((name) => ({ name }))
            )
          }
        />
      </div>

      <button onClick={autoGenerateDescriptions} disabled={loading || !isFormValid}>
        {loading ? "Generating..." : "Generate Descriptions"}
      </button>

      {loading && <div className="spinner">Loading...</div>}

      <div>
        <h2>Generated Competency Descriptions</h2>
        {generatedDescriptions.map((desc, index) => (
          <div className="competency-card" key={index}>
            <h3>{desc.competency}</h3>
            <div className="competency-levels">
              {Object.entries(desc.levels).map(([level, description]) => (
                <div key={level} className="competency-level">
                  <strong>{level}:</strong> <span>{description}</span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default CompetencyFramework;
